package e

const (
	// SUCCESS success
	SUCCESS = 200
	// ERROR error
	ERROR = 500
	// INVALID_PARAMS invalid params
	INVALID_PARAMS = 400

	// ERROR_EXIST_TAG exist tag
	ERROR_EXIST_TAG = 10001
	// ERROR_NOT_EXIST_TAG not exist tag
	ERROR_NOT_EXIST_TAG = 10002
	// ERROR_NOT_EXIST_ARTICLE not exist article
	ERROR_NOT_EXIST_ARTICLE = 10003

	// ERROR_AUTH_CHECK_TOKEN_FAIL check token fail
	ERROR_AUTH_CHECK_TOKEN_FAIL = 20001
	// ERROR_AUTH_CHECK_TOKEN_TIMEOUT token timeout
	ERROR_AUTH_CHECK_TOKEN_TIMEOUT = 20002
	// ERROR_AUTH_TOKEN auth token error
	ERROR_AUTH_TOKEN = 20003
	// ERROR_AUTH error auth
	ERROR_AUTH = 20004
)
